### ISSUE TITLE
Access the data from DELETE Request

### ISSUE THREAD

**Issue by etruta** [NinjasCL/pw-rest#1]
Is not possible access the data body from DELETE Request .

This sample below try to get the `device_token` parameter , but it's empty.

In GET and POST Methods, it's ok.

~~~
if (Request::isDelete()) {
    $device_token = trim($sanitizer->text(Request::getParam('device_token')));
    echo($device_token); // is empty
}
~~~

**Comment by clsource** [comment]
Thanks I will look into it and inform any progress :)

**Comment by clsource** [comment]
Ok I made some tests and it seems the problem is that you are sending the data as `application/x-www-form-urlencoded` when you need to pass the data as a json object with the header `application/json`.

Here is a Postman Screenshot

![captura de pantalla 2017-05-15 a las 2 40 04 p m](https://cloud.githubusercontent.com/assets/292738/26073291/6ddef8bc-397c-11e7-8f0e-38f40769718a.png)

And it works well using the code

```php
<?php
namespace App;

include_once './rest/core/rest.php';

use Rest\Request as Request;

if(Request::isDelete())
{
	$device_token = trim($sanitizer->text(Request::getParam('device_token')));

	die($device_token);
}

```

Happy to help 👍  Cheers.
